"""add confirm mail fields for users model.

Revision ID: 357dbfda35e3
Revises: af875027dd30
Create Date: 2024-08-03 20:41:36.338587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357dbfda35e3'
down_revision: Union[str, None] = 'af875027dd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail_confirm_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_confirm_mail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirm_mail')
    op.drop_column('users', 'mail_confirm_code')
    # ### end Alembic commands ###
