"""Edit type for mail confirm code.

Revision ID: 413dd314b99d
Revises: 5b01b0febee5
Create Date: 2024-11-18 19:08:50.629367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413dd314b99d'
down_revision: Union[str, None] = '5b01b0febee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
