"""Edit type for mail confirm code.

Revision ID: 416d45197fb1
Revises: 413dd314b99d
Create Date: 2024-11-18 19:15:55.198703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416d45197fb1'
down_revision: Union[str, None] = '413dd314b99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN mail_confirm_code TYPE INTEGER USING mail_confirm_code::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mail_confirm_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
