"""edit field name for users model.

Revision ID: 5b01b0febee5
Revises: 357dbfda35e3
Create Date: 2024-08-07 14:47:03.958183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b01b0febee5'
down_revision: Union[str, None] = '357dbfda35e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clicks_per_sec', sa.Float(), nullable=True))
    op.drop_column('users', 'blocks_per_sec')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocks_per_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'clicks_per_sec')
    # ### end Alembic commands ###
