"""add mining chance model.

Revision ID: 67edbf23910c
Revises: 416d45197fb1
Create Date: 2024-11-24 16:13:38.250296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67edbf23910c'
down_revision: Union[str, None] = '416d45197fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_chance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_at_calc', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_chance')
    # ### end Alembic commands ###
