"""add ondelete for referer.

Revision ID: af875027dd30
Revises: 3a853d952127
Create Date: 2024-07-19 19:58:38.268962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af875027dd30'
down_revision: Union[str, None] = '3a853d952127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_referer_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referer'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_referer_fkey', 'users', 'users', ['referer'], ['id'])
    # ### end Alembic commands ###
