"""Initial migration.

Revision ID: d7415e91f986
Revises: 
Create Date: 2024-07-16 15:20:31.703770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7415e91f986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('referral_link', sa.String(), nullable=False),
    sa.Column('referer', sa.Integer(), nullable=True),
    sa.Column('blocks_balance', sa.Float(), nullable=True),
    sa.Column('blocks_per_sec', sa.Float(), nullable=True),
    sa.Column('blocks_per_click', sa.Float(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('last_update_time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['referer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_at_mine', sa.Date(), nullable=False),
    sa.Column('redis_key', sa.String(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_items_redis_key'), 'game_items', ['redis_key'], unique=False)
    op.create_table('boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('redis_key', sa.String(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_at_create', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('game_item_id', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('best_price', sa.Float(), nullable=True),
    sa.Column('best_price_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_price_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_item_id'], ['game_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lots')
    op.drop_table('notifications')
    op.drop_table('boosts')
    op.drop_index(op.f('ix_game_items_redis_key'), table_name='game_items')
    op.drop_table('game_items')
    op.drop_table('users')
    # ### end Alembic commands ###
